[package]
name = "abstract_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
googletest = "0.14.2"
itertools = "0.14.0"
