[package]
name = "onoro-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.5"
multiqueue = "0.3"
cooperate = { path = "./cooperate" }
onoro = { path = "./onoro" }
pprof = { version = "0.11", features = ["flamegraph"] }
rand = "0.8"

[profile.release]
opt-level = 3
debug-assertions = false
overflow-checks = false
lto = "fat"
