[package]
name = "onoro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebra = { path = "../algebra" }
array-macro = "2.1"
arrayvec = "0.7"
num-traits = "0.2"
rand = "0.8"
