[package]
name = "onoro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebra = { path = "../algebra" }
arrayvec = "0.7"
rand = "0.8"
union_find = { path = "../union_find" }
