[package]
name = "cardinality_estimate"
version = "0.1.0"
edition = "2024"

[dependencies]
onoro = { path = "../onoro" }
onoro_impl = { path = "../onoro_impl" }
rand = "0.9.1"

[profile.release]
lto = true
codegen-units = 1
strip = true
