name: Format

on:
  push:
  pull_request:
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Onoro
        uses: actions/checkout@v2
        with:
          path: onoro
          submodules: recursive
      - name: Install prettier
        working-directory: onoro/web
        run: |
          npm install
      - name: Run prettier
        working-directory: onoro/web
        run: |
          npx prettier -c .
